export const CHECK_CLASS_CODE_REQUEST = 'users/CHECK_CLASS_CODE_REQUEST';
export const CHECK_USER_VERIFICATION_CODE_REQUEST = 'users/CHECK_USER_VERIFICATION_CODE_REQUEST';
export const RESET_USER_PASSWORD_REQUEST = 'user/RESET_USER_PASSWORD_REQUEST';
export const SEND_PASSWORD_RECOVERY_LINK_REQUEST = 'users/SEND_PASSWORD_RECOVERY_LINK_REQUEST';
export const SIGN_IN_REQUEST = 'users/SIGN_IN_REQUEST';
export const SIGN_UP_REQUEST = 'users/SIGN_UP_REQUEST';
export const UPDATE_USER_REQUEST = 'users/UPDATE_USER_REQUEST';
export const AUTO_GENERATE_USERNAME_REQUEST = 'users/AUTO_GENERATE_USERNAME_REQUEST';
