# Anchors =================================================
ANCHOR_HORIZONTAL_MARGIN = 11.5 # mm
ANCHOR_WIDTH = 12.5 # mm
ANCHOR_HEIGHT = 12.5 # mm
ANCHOR_LEFT_MARGIN = ANCHOR_HORIZONTAL_MARGIN # mm
ANCHOR_RIGHT_MARGIN = ANCHOR_HORIZONTAL_MARGIN + ANCHOR_WIDTH # mm
ANCHOR_TOP_MARGIN = 9 # mm
ANCHOR_BOTTOM_MARGIN = 19.65 + ANCHOR_HEIGHT * 0.5 # mm

MM_TO_POINTS_CROP_COEF = 2.7 # ~2.8 pts in 1 mm, but take 2.7 for extra space when crop the page
ANCHOR_TOP_MARGIN_PT = ANCHOR_TOP_MARGIN * MM_TO_POINTS_CROP_COEF
ANCHOR_BOTTOM_MARGIN_PT = ANCHOR_BOTTOM_MARGIN * MM_TO_POINTS_CROP_COEF
ANCHOR_LEFT_MARGIN_PT = ANCHOR_LEFT_MARGIN * MM_TO_POINTS_CROP_COEF
ANCHOR_RIGHT_MARGIN_PT = (ANCHOR_RIGHT_MARGIN - ANCHOR_WIDTH) * MM_TO_POINTS_CROP_COEF

# Markup ==================================================

FOOTSKIP = ANCHOR_BOTTOM_MARGIN + 3 # mm

# TODO: use in coordinates calculations
E_HEADHEIGHT = 14.5 # mm
PF_HEADHEIGHT = 15.5 # mm

E_INSTRUCTIONS_TOP_MARGIN = 2 # mm
E_INSTRUCTIONS_TOP_MARGIN1 = 2 # mm
PF_INSTRUCTIONS_TOP_MARGIN = -2 # mm
PF_INSTRUCTIONS_TOP_MARGIN1 = -0.8 # mm

E_INSTRUCTIONS_BOTTOM_MARGIN = 3.5 # mm
E_INSTRUCTIONS_BOTTOM_MARGIN1 = 3.5 # mm
PF_INSTRUCTIONS_BOTTOM_MARGIN = 7.5 # mm
PF_INSTRUCTIONS_BOTTOM_MARGIN1 = 6.3 # mm

# Corner Marks ============================================

# The position of the corner markings from the side of the paper
CORNER_MARK_LEFT = 10.0 # mm
CORNER_MARK_RIGHT = 10.0 # mm
CORNER_MARK_TOP = 12.0 # mm
CORNER_MARK_BOTTOM = 12.0 # mm
CORNER_MARK_LENGTH = 20.0 # mm
