export const ANSWER_SHEET_ZIP_REQUEST = 'assessments/ANSWER_SHEET_ZIP_REQUEST';
export const GENERATE_ANSWER_SHEET_REQUEST = 'assessments/GENERATE_ANSWER_SHEET_REQUEST';
export const GET_ANSWER_SHEET_RESULT_REQUEST = 'assessments/GET_ANSWER_SHEET_RESULT_REQUEST';
export const PREVIEW_ANSWER_SHEET_REQUEST = 'assessments/PREVIEW_ANSWER_SHEET_REQUEST';
export const SET_ANSWER_SHEET_PREVIEW = 'assessments/SET_ANSWER_SHEET_PREVIEW';
export const SET_ANSWER_SHEET_RESULT = 'assessments/SET_ANSWER_SHEET_RESULT';
export const SET_ANSWER_SHEET_SCAN_LOADING = 'assessments/SET_ANSWER_SHEET_SCAN_LOADING';
