export const ANSWER_SHEET_ITEM_SCAN_REQUEST = 'assessments/ANSWER_SHEET_ITEM_SCAN_REQUEST';
export const ANSWER_SHEET_ITEM_SCAN_SUCCESS = 'assessments/ANSWER_SHEET_ITEM_SCAN_SUCCESS';
export const ANSWER_SHEET_SCAN_REQUEST = 'assessments/ANSWER_SHEET_SCAN_REQUEST';
export const DELETE_ANSWER_SHEET_SCAN_REQUEST = 'assessments/DELETE_ANSWER_SHEET_SCAN_REQUEST';
export const DELETE_SCAN_SESSION_REQUEST = 'assessments/DELETE_SCAN_SESSION_REQUEST';
export const SET_ANSWER_SHEET_SCAN_LOADING = 'assessments/SET_ANSWER_SHEET_SCAN_LOADING';
