export const CREATE_GENERIC_PREVIEW_REQUEST = 'generic_preview/CREATE_GROUPS_REQUEST';
export const CREATE_GENERIC_PREVIEW_SUCCESS = 'generic_preview/CREATE_GENERIC_PREVIEW_SUCCESS';
export const CREATE_DOWNLOAD_GENERIC_REQUEST = 'generic_preview/CREATE_DOWNLOAD_GENERIC_REQUEST';
export const CREATE_DOWNLOAD_GENERIC_SUCCESS = 'generic_preview/CREATE_DOWNLOAD_GENERIC_SUCCESS';
export const CHECK_GENERIC_GENERATION_REQUEST = 'generic_preview/CHECK_GENERIC_GENERATION_REQUEST';
export const GET_ANSWER_SHEET_ARCHIVE_REQUEST = 'generic_preview/GET_ANSWER_SHEET_ARCHIVE_REQUEST';
export const UPDATE_ANSWER_SHEET_ARCHIVE_REQUEST = 'generic_preview/UPDATE_ANSWER_SHEET_ARCHIVE_REQUEST';
