# Generated by Django 2.2 on 2020-11-17 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0007_group_code'),
        ('users', '0005_auto_20200626_1011'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('kind', models.CharField(choices=[('email_confirmation', 'Email confirmation')], default='email_confirmation', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='groups.Group')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='users.Student')),
            ],
        ),
    ]
