# Generated by Django 2.2 on 2020-12-17 11:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20201217_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='groups.Group'),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='kind',
            field=models.CharField(choices=[('email_confirmation_for_student', 'Email confirmation for student'), ('email_confirmation_for_user', 'Email confirmation for user')], default='email_confirmation_for_user', max_length=100),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verification_codes', to='users.Student'),
        ),
    ]
