# Generated by Django 2.2 on 2020-12-18 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20201217_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='verificationcode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
