# Generated by Django 2.2 on 2020-12-30 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_verificationcode_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_keep_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
