# Generated by Django 2.2 on 2021-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_user_is_keep_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_generic_popup_show',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='kind',
            field=models.CharField(choices=[('email_confirmation_for_student', 'Email confirmation for student'), ('email_confirmation_for_user', 'Email confirmation for user'), ('password_reset', 'Password reset')], default='email_confirmation_for_user', max_length=100),
        ),
    ]
