# Generated by Django 2.2 on 2021-02-10 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20210208_0759'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verificationcode',
            name='student',
        ),
    ]
