# Generated by Django 2.2 on 2021-07-27 22:53

import django.contrib.postgres.fields.jsonb
from django.db import migrations
import users.models.user


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20210629_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enabled_tutorials',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.user.get_enabled_tutorials_default_dict),
        ),
        migrations.AddField(
            model_name='user',
            name='popups_progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.user.get_popups_progress_default_dict),
        ),
        migrations.AddField(
            model_name='user',
            name='tutorials_progress',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=users.models.user.get_tutorial_progress_default_dict),
        ),
    ]
