# Generated by Django 2.2 on 2022-02-28 06:40

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_loginhistory'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='verificationcode',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='verificationcode',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
