# Generated by Django 2.2 on 2022-03-30 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20220228_0640'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='verificationcode',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='is_info_page_passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='verificationcode',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
