# Generated by Django 2.2 on 2022-05-25 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20220330_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_device',
            field=models.CharField(blank=True, choices=[('android', 'Android App'), ('website', 'Web version'), ('ios', 'IOs App')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sign_up_device',
            field=models.CharField(blank=True, choices=[('android', 'Android App'), ('website', 'Web version'), ('ios', 'IOs App')], max_length=30, null=True),
        ),
    ]
