# Generated by Django 2.2 on 2022-06-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_auto_20220525_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='enable_email_subscription',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_email_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sent_emails_counter',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
