# Generated by Django 2.2 on 2022-06-20 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_auto_20220622_1016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loginhistory',
            old_name='user_id',
            new_name='user',
        ),
    ]
