# Generated by Django 2.2 on 2022-08-01 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20220720_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='first'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='last'),
        ),
        migrations.AlterField(
            model_name='user',
            name='school_type',
            field=models.CharField(blank=True, choices=[('university', 'University'), ('high_school', 'High school'), ('middle_school', 'Middle school'), ('elementary', 'Elementary')], max_length=255, null=True, verbose_name='school'),
        ),
    ]
