# Generated by Django 2.2 on 2022-10-06 18:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_login_device',
            field=models.CharField(blank=True, choices=[('android', 'Android App'), ('website', 'Web version'), ('ios', 'IOs App'), ('mobile', 'Mobile'), ('mobile_android', 'Mobile (A)'), ('mobile_ios', 'Mobile (iOS)')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='sign_up_device',
            field=models.CharField(blank=True, choices=[('android', 'Android App'), ('website', 'Web version'), ('ios', 'IOs App'), ('mobile', 'Mobile'), ('mobile_android', 'Mobile (A)'), ('mobile_ios', 'Mobile (iOS)')], max_length=30, null=True),
        ),
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('assessment_created', 'Assessment created'), ('class_created', 'Class created'), ('result_created', 'Result created')], max_length=255)),
                ('last_created_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
