const AFTER_RELEASE_TUTORIAL_KEY = 'AfterRelease';
const ASK_TO_WRITE_NEATLY_TUTORIAL_KEY = 'AskToWriteNeatly';
const CREATE_ASSESSMENT_TUTORIAL_KEY = 'CreateAssessment';
const CUSTOM_TUTORIAL_KEY = 'Custom';
const DISTRIBUTE_REGULAR_AS_TUTRIAL_KEY = 'DistributeRegularAS';
const GENERIC_TUTORIAL_KEY = 'Generic';
const NO_STUDENTS_TUTORIAL_KEY = 'NoStudents';
const ONLINE_TUTORIAL_KEY = 'Online';
const SCAN_WRITTEN_AS_TUTORIAL_KEY = 'ScanWrittenAS';
const STUDENT_INSTRUCTIONS_TUTORIAL_KEY = 'StudentInstructions';
const VIEW_RESULTS_TUTORIAL_KEY = 'ViewResults'; // unnecessary?
const TEACHER_RESULTS_TUTORIAL_KEY = 'ViewResults';
const DISTRIBUTE_GENERIC_AS_TUTORIAL_KEY = 'DistributeGenericAS';
const SCAN_WRITTEN_GENERIC_AS_TUTORIAL_KEY = 'ScanGenericAS';
const STUDENTS_MUST_FILL_CIRCLES_TUTORIAL_KEY = 'StudentsMustFillCircles';
const DOWNLOAD_APP_TO_SCAN_AS_TUTORIAL_KEY = 'DownloadAppToScanAS';
const SETTINGS_HELP_TUTORIAL_KEY = 'SettingsHelp';

export {
  AFTER_RELEASE_TUTORIAL_KEY,
  ASK_TO_WRITE_NEATLY_TUTORIAL_KEY,
  CREATE_ASSESSMENT_TUTORIAL_KEY,
  CUSTOM_TUTORIAL_KEY,
  DISTRIBUTE_GENERIC_AS_TUTORIAL_KEY,
  DISTRIBUTE_REGULAR_AS_TUTRIAL_KEY,
  DOWNLOAD_APP_TO_SCAN_AS_TUTORIAL_KEY,
  GENERIC_TUTORIAL_KEY,
  NO_STUDENTS_TUTORIAL_KEY,
  ONLINE_TUTORIAL_KEY,
  SCAN_WRITTEN_AS_TUTORIAL_KEY,
  SCAN_WRITTEN_GENERIC_AS_TUTORIAL_KEY,
  SETTINGS_HELP_TUTORIAL_KEY,
  STUDENT_INSTRUCTIONS_TUTORIAL_KEY,
  STUDENTS_MUST_FILL_CIRCLES_TUTORIAL_KEY,
  TEACHER_RESULTS_TUTORIAL_KEY,
  VIEW_RESULTS_TUTORIAL_KEY,
};
