from django.conf.urls import url
from assessments.views import (
    AnswerSheetZipView,
    AssessmentAnalysisView,
    AssessmentAnswersView,
    AssessmentAveragesView,
    AssessmentDetailView,
    AssessmentResultForStudentView,
    AssessmentResultsView,
    AssessmentResultsForMobileView,
    AssessmentsListCreateView,
    AssessmentFileUploadView,
    AssessmentBatchFileUploadView,
    AssignAssessmentView,
    AssignedAssessmentsListView,
    CheckAssessmentNameView,
    CheckStatusAnswerSheetView,
    CompletedAssessmentsListView,
    CopyAssessmentView,
    DeleteAssessmentView,
    DeleteResultsView,
    DeleteScanAnswerSheetView,
    DeleteScanSessionView,
    DeleteAssessmentFileView,
    DeleteAssessmentFilesView,
    GenerateAnswerSheetView,
    GenerateGenericAnswerSheetView,
    GenericResultsRecognitionView,
    GenericDataRecognitionView,
    GenericDataCroppingView,
    GetAccuracyTipsView,
    GetAnswerSheetCoordinatesView,
    GetAssessmentNameView,
    PreviewAnswerSheetView,
    PreviewGenericAnswerSheetView,
    ResultAnswerSheetView,
    ResultGenericAnswerSheetView,
    ResultsRecognitionView,
    ResultDetailView,
    SaveStudentAnswersView,
    ScanAnswerSheetItemView,
    ScanAnswerSheetView,
    StartAssessmentView,
    StudentAssessmentDetailView,
    StudentSubmitAssessmentView,
    StudentProcessAssessmentView,
    UnassignAssessmentView,
    UpdateAnswerNeedGradingView,
    UpdateAssessmentNeedGradingView,
    UpdateAssessmentStatusView,
    UpdateResultItemNeedGradingView,
    UpdateResultNeedGradingView,
    UpdateStudentMarkView,
    UpdateResultsStatusesView,
    DownloadResultsView,
    ViewFullScansView,
    DownloadFullScansView,
)

urlpatterns = [
    url(r"^assessments/(?P<assessment_id>\d+)/$",
        AssessmentDetailView.as_view(), name="assessments_detail"),
    url(r"^assessments/$", AssessmentsListCreateView.as_view(), name="assessments"),
    url(r"^assessments/accuracy_tips/$", GetAccuracyTipsView.as_view(), name="assessment_accuracy_tips"),
    url(r"^assessments/check_name/$",
        CheckAssessmentNameView.as_view(), name="answer_sheet_result"),
    url(r"^assessments/delete/$", DeleteAssessmentView.as_view(), name="delete_assessment"),
    url(r"^assessments/name/$", GetAssessmentNameView.as_view(), name="answer_sheet_result"),
    url(r"^assessments/(?P<assessment_id>\d+)/assign/$", AssignAssessmentView.as_view(), name="assign_assessment"),
    url(r"^assessments/(?P<assessment_id>\d+)/status/$",
        UpdateAssessmentStatusView.as_view(), name="update_status_assessment"),
    url(r"^assessments/(?P<assessment_id>\d+)/unassign/$", UnassignAssessmentView.as_view(), name="unassign_assessment"),
    url(r"^answer_sheets/zip/", AnswerSheetZipView.as_view(), name='answer_sheet_zip'),
    url(r"^answer_sheets/check_status/$", CheckStatusAnswerSheetView.as_view(), name="check_status_answer_sheet"),
    url(r"^answer_sheets/generate/generic/$",
        GenerateGenericAnswerSheetView.as_view(), name="generate_generic_answer_sheet"),
    url(r"^answer_sheets/preview/generic/$",
        PreviewGenericAnswerSheetView.as_view(), name="generic_answer_sheet_preview"),
    url(r"^answer_sheets/generic_results/$",
        ResultGenericAnswerSheetView.as_view(), name="result_generic_answer_sheet"),
    url(r"^assessment_for_student/(?P<assessment_id>\d+)/$",
        StudentAssessmentDetailView.as_view(), name="student_assessment_detail"),
    url(r"^assessments/(?P<assessment_id>\d+)/analysis/$",
        AssessmentAnalysisView.as_view(), name="assessment_analysis"),
    url(r"^assessments/(?P<assessment_id>\d+)/answers/$", AssessmentAnswersView.as_view(), name="assessment_answers"),
    url(r"^assessments/(?P<assessment_id>\d+)/averages/$",
        AssessmentAveragesView.as_view(), name="assessment_averages"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/$", AssessmentResultsView.as_view(), name="assessment_results"),
    url(r"^assessments/(?P<assessment_id>\d+)/mobile_results/$", AssessmentResultsForMobileView.as_view(), name="assessment_results_for_mobile"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/(?P<result_id>\d+)/$", ResultDetailView.as_view(), name="result_detail"),
    url(r"^assessments/(?P<assessment_id>\d+)/copy/$", CopyAssessmentView.as_view(), name="copy_assessment"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/delete/", DeleteResultsView.as_view(), name="delete_results"),
    url(r"^assessments/(?P<assessment_id>\d+)/answer_sheet/generate/$",
        GenerateAnswerSheetView.as_view(), name="answer_sheet_generate"),
    url(r"^assessments/(?P<assessment_id>\d+)/answer_sheet/preview/$",
        PreviewAnswerSheetView.as_view(), name="answer_sheet_preview"),
    url(r"^assessments/(?P<assessment_id>\d+)/answer_sheets/(?P<answer_sheet_id>\d+)/result/$",
        ResultAnswerSheetView.as_view(), name="answer_sheet_result"),
    url(r"^assessments/recognition_batch/(?P<batch_id>\d+)/result/$",
        ResultsRecognitionView.as_view(), name="recognition_result"),
    url(r"^assessments/recognition_batch/(?P<batch_id>\d+)/recognition_results/$",
        GenericDataRecognitionView.as_view(), name="recognition_generic_data"),
    url(r"^assessments/recognition_batch/(?P<batch_id>\d+)/cropping_results/$",
        GenericDataCroppingView.as_view(), name="save_cropping_data"),
    url(r"^assessments/(?P<assessment_id>\d+)/generic_results/$",
        GenericResultsRecognitionView.as_view(), name="recognition_generic_results"),
    url(r"^assessments/(?P<assessment_id>\d+)/item_scan/$",
        ScanAnswerSheetItemView.as_view(), name="scan_answer_sheet_item"),
    url(r"^assessments/(?P<assessment_id>\d+)/scan/$", ScanAnswerSheetView.as_view(), name="scan_answer_sheet"),
    url(r"^assessments/(?P<assessment_id>\d+)/student_marks/(?P<mark_id>\d+)/$",
        UpdateStudentMarkView.as_view(), name="update_mark"),
    url(r"^assessments/(?P<assessment_id>\d+)/scans/(?P<id>\d+)/delete/$",
        DeleteScanAnswerSheetView.as_view(), name="delete_scan_answer_sheet"),
    url(r"^assessments/(?P<assessment_id>\d+)/scans/delete_session/$",
        DeleteScanSessionView.as_view(), name="delete_session"),
    url(r"^assessments/(?P<assessment_id>\d+)/submit/(?P<completed_assessment_id>\d+)/$",
        StudentSubmitAssessmentView.as_view(), name="student_submit"),
    url(r"^assessments/assigned/$", AssignedAssessmentsListView.as_view(), name="assigned_assessments"),
    url(r"^assessments/completed/$", CompletedAssessmentsListView.as_view(), name="completed_assessments"),
    url(r"^assessments/(?P<assessment_id>\d+)/student_results/(?P<completed_assessment_id>\d+)/$",
        AssessmentResultForStudentView.as_view(), name="results_for_student"),
    url(r"^answer_sheets/(?P<answer_sheet_id>\d+)/coordinates/$",
        GetAnswerSheetCoordinatesView.as_view(), name="get_answer_sheet_coordinates"),
    url(r"^assessments/(?P<assessment_id>\d+)/save_student_answers/(?P<completed_assessment_id>\d+)/$",
        SaveStudentAnswersView.as_view(), name="save_student_answers"),
    url(r"^assessments/(?P<assessment_id>\d+)/start/$", StartAssessmentView.as_view(), name="start_assessment"),
    url(r"^assessment_for_student/(?P<assessment_id>\d+)/process_assessment/$",
        StudentProcessAssessmentView.as_view(), name="process_assessment"),
    url(r"^assessments/(?P<assessment_id>\d+)/files/$", AssessmentFileUploadView.as_view(), name="assessment_file_upload"),
    url(r"^assessments/(?P<assessment_id>\d+)/batch_files/$",
        AssessmentBatchFileUploadView.as_view(), name="assessment_batch_file_upload"),
    url(r"^assessments/(?P<assessment_id>\d+)/files/(?P<id>\d+)/$",
        DeleteAssessmentFileView.as_view(), name="delete_assessment_file"),
    url(r"^assessments/(?P<assessment_id>\d+)/files/delete/$",
        DeleteAssessmentFilesView.as_view(), name="delete_assessment_files"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/need_grading/$",
        UpdateResultItemNeedGradingView.as_view(), name="update_need_grading"),
    url(r"^assessments/(?P<assessment_id>\d+)/need_grading/$",
        UpdateAssessmentNeedGradingView.as_view(), name="update_assessment_need_grading"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/(?P<result_id>\d+)/need_grading/$",
        UpdateResultNeedGradingView.as_view(), name="update_result_need_grading"),
    url(r"^assessments/(?P<assessment_id>\d+)/answers/need_grading/$",
        UpdateAnswerNeedGradingView.as_view(), name="update_answer_need_grading"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/statuses/$",
        UpdateResultsStatusesView.as_view(), name="update_results_statuses"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/download/$",
        DownloadResultsView.as_view(), name="download_results"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/(?P<result_id>\d+)/full_scans/$",
        ViewFullScansView.as_view(), name="view_full_scans"),
    url(r"^assessments/(?P<assessment_id>\d+)/results/(?P<result_id>\d+)/download_full_scans/$",
        DownloadFullScansView.as_view(), name="download_full_scans"),
]
