# Generated by Django 2.2 on 2020-03-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('blue', '#42a5f5'), ('brown', '#8d6e63'), ('green', '#66bb6a'), ('indigo', '#5c6bc0'), ('lime', '#d4e157'), ('orange', '#ffa726'), ('pink', '#ec407a'), ('purple', '#ab47bc'), ('red', '#ef5350'), ('teal', '#26a69a')], default='pink', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
