# Generated by Django 2.2 on 2020-04-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_auto_20200325_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to='users.Student'),
        ),
    ]
