# Generated by Django 2.2 on 2021-07-29 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0008_group_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='category_last_img_number',
            field=models.IntegerField(null=True),
        ),
    ]
