# Generated by Django 2.2 on 2022-02-22 07:33

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0009_group_category_last_img_number'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='group',
            managers=[
                ('manager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
