import React from 'react';
import BackspaceIcon from '@material-ui/icons/Backspace';
import { IconLeftArrow, IconRightArrow } from 'components/Svgs';

export const OPTIONS = {
  firstLine: [
    { label: 'a^b', len: 1, move: 'left', expression: '^{ }' },
    { label: '\\sqrt{}', len: 1, move: 'left', expression: '\\sqrt{ }' },
    { label: '\\pi', len: 2, move: null, expression: '\\pi ' },
    { label: '\\log', len: 5, move: 'left', expression: '\\log \\left(\\right)' },
    { label: '\\sin', len: 5, move: 'left', expression: '\\sin \\left(\\right)' },
    { label: '\\cos', len: 5, move: 'left', expression: '\\cos \\left(\\right)' },
    { label: '\\tan', len: 5, move: 'left', expression: '\\tan \\left(\\right)' },
    { label: '\\csc', len: 5, move: 'left', expression: '\\csc \\left(\\right)' },
    { label: '\\sec', len: 5, move: 'left', expression: '\\sec \\left(\\right)' },
    { label: '\\cot', len: 5, move: 'left', expression: '\\cot \\left(\\right)' },
  ],
  secondLine: [
    { label: 'a^2', len: 2, move: 'left', expression: '^{2}' },
    { label: '\\sqrt[n]{}', len: 1, move: 'up', expression: '\\sqrt[]{}' },
    { label: '\\ln', len: 4, move: 'left', expression: '\\ln \\left(\\right)' },
    { label: '\\log_{a}', len: 5, move: 'up', expression: '\\log _\\left(\\right)' },
    { label: '\\sin^{-1}', len: 7, move: 'left', expression: '\\sin ^{-1}\\left(\\right)' },
    { label: '\\cos^{-1}', len: 7, move: 'left', expression: '\\cos ^{-1}\\left(\\right)' },
    { label: '\\tan^{-1}', len: 7, move: 'left', expression: '\\tan ^{-1}\\left(\\right)' },
    { label: '\\csc^{-1}', len: 7, move: 'left', expression: '\\csc ^{-1}\\left(\\right)' },
    { label: '\\sec^{-1}', len: 7, move: 'left', expression: '\\sec ^{-1}\\left(\\right)' },
    { label: '\\cot^{-1}', len: 7, move: 'left', expression: '\\cot ^{-1}\\left(\\right)' },
  ],
};

export const MOBILE_OPTIONS = {
  firstLine: [
    { label: '\\log', len: 5, type: 'func', move: 'left', expression: '\\log \\left(\\right)' },
    { label: '\\sin', len: 5, type: 'func', move: 'left', expression: '\\sin \\left(\\right)' },
    { label: '\\cos', len: 5, type: 'func', move: 'left', expression: '\\cos \\left(\\right)' },
    { label: '\\tan', len: 5, type: 'func', move: 'left', expression: '\\tan \\left(\\right)' },
    { label: '7', len: 1, type: 'number', move: null, expression: '7' },
    { label: '8', len: 1, type: 'number', move: null, expression: '8' },
    { label: '9', len: 1, type: 'number', move: null, expression: '9' },
    { label: ':', len: 1, type: 'func', expression: '\\frac' },
    { label: '\\sqrt{}', len: 1, type: 'func', move: null, expression: '\\sqrt{ }' },
    { label: '\\sqrt[n]{}', len: 1, type: 'func', move: 'up' },
  ],
  secondLine: [
    { label: '\\log_{a}', len: 5, type: 'func', move: 'up', expression: '\\log _\\left(\\right)' },
    {
      label: '\\sin^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\sin ^{-1}\\left(\\right)',
    },
    {
      label: '\\cos^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\cos ^{-1}\\left(\\right)',
    },
    {
      label: '\\tan^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\tan ^{-1}\\left(\\right)',
    },
    { label: '4', len: 1, type: 'number', move: null, expression: '4' },
    { label: '5', len: 1, type: 'number', move: null, expression: '5' },
    { label: '6', len: 1, type: 'number', move: null, expression: '6' },
    { label: 'x', len: 1, type: 'func', move: null, expression: '\\cdot' },
    { label: '(', len: 1, type: 'func', move: null, expression: '\\left(' },
    { label: ')', len: 1, type: 'func', move: null, expression: '\\right)' },
  ],
  thirdLine: [
    { label: '\\ln', len: 4, move: 'left', expression: '\\ln \\left(\\right)' },
    { label: '\\csc', len: 5, type: 'func', move: 'left', expression: '\\csc \\left(\\right)' },
    { label: '\\sec', en: 5, type: 'func', move: 'left', expression: '\\sec \\left(\\right)' },
    { label: '\\cot', len: 5, type: 'func', move: 'left', expression: '\\cot \\left(\\right)' },
    { label: '1', len: 1, type: 'number', move: null, expression: '1' },
    { label: '2', len: 1, type: 'number', move: null, expression: '2' },
    { label: '3', len: 1, type: 'number', move: null, expression: '3' },
    { label: '-', len: 1, type: 'func', move: null, expression: '-' },
    { label: 'a^b', len: 1, type: 'func', move: null, expression: '^' },
    {
      label: <BackspaceIcon style={{ fontSize: 14 }} />,
      len: 1,
      type: 'move',
      move: null,
      expression: 'backspace',
    },
  ],
  fourthLine: [
    { label: '\\pi', len: 2, type: 'func', move: null, expression: '\\pi ' },
    {
      label: '\\csc^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\csc ^{-1}\\left(\\right)',
    },
    {
      label: '\\sec^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\sec ^{-1}\\left(\\right)',
    },
    {
      label: '\\cot^{-1}',
      len: 7,
      type: 'func',
      move: 'left',
      expression: '\\cot ^{-1}\\left(\\right)',
    },
    { label: '0', len: 1, type: 'number', move: null, expression: '0' },
    { label: '.', len: 1, type: 'number', move: null, expression: '.' },
    { label: '=', len: 1, type: 'func', move: null, expression: '=' },
    { label: '+', len: 1, type: 'func', move: null, expression: '+' },
    {
      label: <IconLeftArrow style={{ fill: '#049EE1', width: 50, height: 18 }} />,
      expression: 'move_left',
      len: 0,
      type: 'move',
    },
    {
      label: <IconRightArrow style={{ fill: '#049EE1', width: 50, height: 18 }} />,
      expression: 'move_rigth',
      len: 0,
      type: 'move',
    },
  ],
};
