# Generated by Django 2.2 on 2020-04-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0005_auto_20200416_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='document',
            field=models.FileField(blank=True, upload_to='answer_sheets/'),
        ),
    ]
