# Generated by Django 2.2 on 2020-05-07 12:46

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200429_0614'),
        ('assessments', '0007_auto_20200429_0905'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheetScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('global_id', models.CharField(max_length=255)),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AnswerSheet')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Student')),
            ],
        ),
        migrations.CreateModel(
            name='RecognitionBatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scans', models.ManyToManyField(blank=True, to='assessments.AnswerSheetScan')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentResultItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', django.contrib.postgres.fields.jsonb.JSONField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('mark', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentItem')),
                ('assessment_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentResult')),
            ],
        ),
        migrations.CreateModel(
            name='AnswerSheetScanItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.ImageField(upload_to='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('answer_sheet_scan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AnswerSheetScan')),
            ],
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='assessment_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assessments.AssessmentResult'),
        ),
    ]
