# Generated by Django 2.2 on 2020-05-08 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0008_auto_20200507_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheetscanitem',
            name='page',
        ),
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='pages',
            field=models.IntegerField(default=1),
        ),
    ]
