# Generated by Django 2.2 on 2020-05-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0009_auto_20200508_0725'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheetscanitem',
            name='page',
            field=models.IntegerField(default=0),
        ),
    ]
