# Generated by Django 2.2 on 2020-05-08 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0010_answersheetscanitem_page'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='number',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='named_page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='unnamed_page_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='assessmentitem',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
