# Generated by Django 2.2 on 2020-05-11 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_auto_20200508_0909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetscanitem',
            name='answer_sheet_scan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.AnswerSheetScan'),
        ),
    ]
