# Generated by Django 2.2 on 2020-05-13 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0011_auto_20200511_0950'),
        ('assessments', '0012_auto_20200511_1044'),
    ]

    operations = [
    ]
