# Generated by Django 2.2 on 2020-05-14 09:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200429_1231'),
        ('assessments', '0012_auto_20200511_1044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresult',
            name='student',
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='email_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='first_name_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='last_name_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='named',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='session_id',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Student'),
        ),
    ]
