# Generated by Django 2.2 on 2020-05-14 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0014_auto_20200514_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognitionbatch',
            name='status',
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready_for_download', 'Ready for download'), ('ready_for_generation', 'Ready for generating'), ('ready_for_scan', 'Ready for scan'), ('scanned', 'Scanned'), ('scanning', 'Scanning')], default='ready_for_generation', max_length=255),
        ),
    ]
