# Generated by Django 2.2 on 2020-05-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_auto_20200514_1142'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccuracyTipsAnswerSheet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accuracy_tips_document', models.FileField(upload_to='answer_sheets/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, upload_to='answer_sheets/')),
                ('is_download', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='document',
        ),
    ]
