# Generated by Django 2.2 on 2020-05-17 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0015_auto_20200514_1142'),
        ('assessments', '0013_merge_20200513_0811'),
    ]

    operations = [
    ]
