# Generated by Django 2.2 on 2020-05-18 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0017_auto_20200518_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='assessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='assessments.AssessmentItem'),
        ),
    ]
