# Generated by Django 2.2 on 2020-05-19 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0016_auto_20200518_0533'),
        ('assessments', '0019_auto_20200518_2200'),
    ]

    operations = [
    ]
