# Generated by Django 2.2 on 2020-05-26 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0021_auto_20200522_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresultitem',
            name='need_grading',
            field=models.BooleanField(default=False),
        ),
    ]
