# Generated by Django 2.2 on 2020-06-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0022_assessmentresultitem_need_grading'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='scientific_notation',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
