# Generated by Django 2.2 on 2020-06-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0023_answer_scientific_notation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='assessment',
        ),
        migrations.AddField(
            model_name='answersheet',
            name='assessments',
            field=models.ManyToManyField(blank=True, to='assessments.Assessment'),
        ),
    ]
