# Generated by Django 2.2 on 2020-06-04 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0024_auto_20200603_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='kind',
            field=models.CharField(choices=[('custom', 'Custom'), ('generic', 'Generic MC'), ('generic_group', 'Generic MC for group')], default='custom', max_length=255),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='named_page_count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='unnamed_page_count',
            field=models.IntegerField(default=1),
        ),
    ]
