# Generated by Django 2.2 on 2020-06-05 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0025_auto_20200604_1105'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheetZip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.FileField(blank=True, upload_to='answer_sheets/')),
                ('is_download', models.BooleanField(default=False)),
                ('kind', models.CharField(choices=[('custom', 'Custom'), ('generic', 'Generic MC')], default='custom', max_length=255)),
                ('uuid', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='AccuracyTipsAnswerSheet',
        ),
    ]
