# Generated by Django 2.2 on 2020-06-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0026_auto_20200605_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='number_of_answers',
            field=models.IntegerField(choices=[(20, 20), (50, 50), (100, 100)], default=20),
        ),
    ]
