# Generated by Django 2.2 on 2020-06-23 14:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0027_answersheet_number_of_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheetscan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='answersheetscan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
