# Generated by Django 2.2 on 2020-07-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0029_auto_20200713_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='unit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
