# Generated by Django 2.2 on 2020-08-04 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0030_answer_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tolerance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
