# Generated by Django 2.2 on 2020-08-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0031_answer_tolerance'),
        ('assessments', '0031_answer_significant_figure'),
    ]

    operations = [
    ]
