# Generated by Django 2.2 on 2020-08-06 09:50

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0032_merge_20200805_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='tolerance_data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
