# Generated by Django 2.2 on 2020-08-07 07:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0033_answer_tolerance_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentresultitem',
            name='mark',
        ),
        migrations.AddField(
            model_name='assessmentresultitem',
            name='unit_image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.CreateModel(
            name='AssessmentResultItemMark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('answer', 'Answer'), ('unit', 'Unit'), ('significant_figure', 'Significant figure')], default='answer', max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('assessment_result_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_item_mark', to='assessments.AssessmentResultItem')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
