# Generated by Django 2.2 on 2020-08-26 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0035_assessmentresult_answer_sheet_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresultitem',
            name='assessment_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='assessments.AssessmentResult'),
        ),
    ]
