# Generated by Django 2.2 on 2020-10-13 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0036_auto_20200826_1233'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresultitem',
            name='correct_answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='correct_answer', to='assessments.Answer'),
        ),
    ]
