# Generated by Django 2.2 on 2020-11-02 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0037_assessmentresultitem_correct_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='number',
            field=models.IntegerField(default=0),
        ),
    ]
