# Generated by Django 2.2 on 2020-12-01 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0038_answer_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresultitem',
            name='assessment_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='assessments.AssessmentItem'),
        ),
    ]
