# Generated by Django 2.2 on 2020-12-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0039_auto_20201201_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='students_changed',
            field=models.BooleanField(default=False),
        ),
    ]
