# Generated by Django 2.2 on 2021-01-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0040_answersheet_students_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='answers_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
