# Generated by Django 2.2 on 2021-01-27 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0041_assessment_answers_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentitem',
            name='max_mark',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
