# Generated by Django 2.2 on 2021-02-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0042_assessmentitem_max_mark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('custom', 'Custom'), ('online', 'Online'), ('generic', 'Generic MC')], default='custom', max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('generating', 'Generating'), ('ready_for_assignment', 'Ready for assignment'), ('ready_for_download', 'Ready for download'), ('ready_for_generation', 'Ready for generating'), ('ready_for_scan', 'Ready for scan'), ('scanned', 'Scanned'), ('scanning', 'Scanning')], default='ready_for_generation', max_length=255),
        ),
    ]
