# Generated by Django 2.2 on 2021-02-11 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0043_auto_20210212_0718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('completed_unassigned', 'Completed unassigned'), ('generating', 'Generating'), ('ready_for_assignment', 'Ready for assignment'), ('ready_for_download', 'Ready for download'), ('ready_for_generation', 'Ready for generating'), ('ready_for_scan', 'Ready for scan'), ('scanned', 'Scanned'), ('scanning', 'Scanning')], default='ready_for_generation', max_length=255),
        ),
    ]
