# Generated by Django 2.2 on 2021-02-15 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0044_auto_20210211_0635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('custom', 'Regular'), ('online', 'Online'), ('generic', 'Multiple choice')], default='custom', max_length=255),
        ),
    ]
