# Generated by Django 2.2 on 2021-02-23 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0045_auto_20210215_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheet',
            name='number_of_answers',
        ),
    ]
