# Generated by Django 2.2 on 2021-02-25 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0046_remove_answersheet_number_of_answers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answersheet',
            old_name='students_changed',
            new_name='changed',
        ),
    ]
