# Generated by Django 2.2 on 2021-03-09 08:53

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0047_auto_20210225_0654'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachments', django.contrib.postgres.fields.ArrayField(base_field=models.FileField(blank=True, null=True, upload_to=''), default=list, size=None)),
                ('timer_value', models.IntegerField(null=True)),
                ('timer_unit', models.CharField(blank=True, choices=[('minutes', 'Minutes'), ('hours', 'Hours'), ('days', 'Days')], max_length=10, null=True)),
                ('release_results_type', models.CharField(blank=True, choices=[('mark', 'Final mark'), ('mark_plus_student_answers', "Final mark + student's answers"), ('mark_plus_student_answers_plus_correct_answers', "Final mark + student's answers + correct answers")], max_length=255, null=True)),
                ('is_auto_release_files_checked', models.BooleanField(default=False)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('is_anti_cheating_mode_checked', models.BooleanField(default=False)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='assessments.Assessment')),
            ],
        ),
    ]
