# Generated by Django 2.2 on 2021-03-14 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_auto_20210310_0925'),
        ('assessments', '0048_assessmentsettings'),
    ]

    operations = [
    ]
