# Generated by Django 2.2 on 2021-03-15 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0048_auto_20210312_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheet',
            name='coordinate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='answersheet',
            name='unnamed_coordinate_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
