# Generated by Django 2.2 on 2021-03-15 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0049_merge_20210314_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentsettings',
            name='assessment',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='assessments.Assessment'),
        ),
    ]
