# Generated by Django 2.2 on 2021-03-18 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0051_completedassessment_result'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completedassessment',
            name='result',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_assessment', to='assessments.AssessmentResult'),
        ),
    ]
