# Generated by Django 2.2 on 2021-03-26 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0052_auto_20210318_0703'),
        ('assessments', '0049_auto_20210315_1025'),
    ]

    operations = [
    ]
