# Generated by Django 2.2 on 2021-03-29 13:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_merge_20210326_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='completedassessment',
            name='student_answers',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completedassessment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
