# Generated by Django 2.2 on 2021-03-31 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0053_merge_20210326_1116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersheetscan',
            name='email_url',
        ),
        migrations.RemoveField(
            model_name='answersheetscan',
            name='first_name_url',
        ),
        migrations.RemoveField(
            model_name='answersheetscan',
            name='global_id',
        ),
        migrations.RemoveField(
            model_name='answersheetscan',
            name='last_name_url',
        ),
        migrations.RemoveField(
            model_name='answersheetscan',
            name='pages',
        ),
    ]
