# Generated by Django 2.2 on 2021-04-05 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0054_auto_20210331_1526'),
        ('assessments', '0054_auto_20210329_1303'),
    ]

    operations = [
    ]
