# Generated by Django 2.2 on 2021-04-08 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0054_auto_20210329_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='type',
            field=models.CharField(choices=[('online', 'Online'), ('paper', 'Paper')], default='paper', max_length=255),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='kind',
            field=models.CharField(choices=[('custom', 'Regular'), ('generic', 'Multiple choice')], default='custom', max_length=255),
        ),
    ]
