# Generated by Django 2.2 on 2021-04-09 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0055_merge_20210405_1736'),
        ('assessments', '0055_auto_20210408_0633'),
    ]

    operations = [
    ]
