# Generated by Django 2.2 on 2021-04-21 10:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0057_completedassessment_release_results_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
