# Generated by Django 2.2 on 2021-04-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0057_completedassessment_release_results_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.FileField(blank=True, upload_to='assessments/')),
                ('file_id', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=50)),
                ('assessment_setting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='assessments.AssessmentSettings')),
            ],
        ),
    ]
