# Generated by Django 2.2 on 2021-04-25 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0058_assessmentfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessmentsettings',
            name='attachments',
        ),
    ]
