# Generated by Django 2.2 on 2021-05-04 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0059_remove_assessmentsettings_attachments'),
        ('assessments', '0058_assessmentsettings_created_at'),
    ]

    operations = [
    ]
