# Generated by Django 2.2 on 2021-05-18 06:07

import assessments.models.assessment_file
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0060_merge_20210504_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, storage=assessments.models.assessment_file.MediaStorage(), upload_to='assessments/'),
        ),
    ]
