# Generated by Django 2.2 on 2021-05-25 13:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0061_auto_20210518_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresultitemmark',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assessmentresultitemmark',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
