# Generated by Django 2.2 on 2021-06-03 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0062_auto_20210525_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentfile',
            name='format',
            field=models.CharField(max_length=100),
        ),
    ]
