# Generated by Django 2.2 on 2021-06-01 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assessments', '0062_auto_20210525_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheetzip',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheet_archives', to=settings.AUTH_USER_MODEL),
        ),
    ]
