# Generated by Django 2.2 on 2021-05-27 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0062_auto_20210525_1303'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecognizedPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name_url', models.TextField(blank=True)),
                ('last_name_url', models.TextField(blank=True)),
                ('email_url', models.TextField(blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='assessmentresult',
            name='recognized_person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='assessments.RecognizedPerson'),
        ),
    ]
