# Generated by Django 2.2 on 2021-05-31 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0063_auto_20210527_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recognizedperson',
            name='email_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recognizedperson',
            name='first_name_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recognizedperson',
            name='last_name_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
