# Generated by Django 2.2 on 2021-06-04 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0064_auto_20210531_0910'),
        ('assessments', '0063_answersheetzip_user'),
        ('assessments', '0063_auto_20210603_1158'),
    ]

    operations = [
    ]
