# Generated by Django 2.2 on 2021-06-09 07:16

import assessments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0065_merge_20210604_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='answer_sheets/'),
        ),
    ]
