# Generated by Django 2.2 on 2021-06-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0065_merge_20210604_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresultitem',
            name='need_grading_for_units',
            field=models.BooleanField(default=False),
        ),
    ]
