# Generated by Django 2.2 on 2021-06-09 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0066_auto_20210609_0716'),
        ('assessments', '0066_assessmentresultitem_need_grading_for_units'),
    ]

    operations = [
    ]
