# Generated by Django 2.2 on 2021-06-15 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0067_merge_20210609_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('generating', 'Generating'), ('ready_for_assignment', 'Ready for assignment'), ('ready_for_download', 'Ready for download'), ('ready_for_generation', 'Ready for generating'), ('ready_for_scan', 'Ready for scan'), ('scanned', 'Scanned'), ('scanning', 'Scanning'), ('scanning_error', 'Scanning error')], default='ready_for_generation', max_length=255),
        ),
    ]
