# Generated by Django 2.2 on 2021-06-24 06:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0067_merge_20210609_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentsettings',
            name='is_released',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='completedassessment',
            name='settings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='completed_assessment', to='assessments.AssessmentSettings'),
        ),
        migrations.AlterField(
            model_name='assessmentsettings',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='assessments.Assessment'),
        ),
    ]
