# Generated by Django 2.2 on 2021-06-18 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0067_merge_20210609_1537'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentfile',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, upload_to='assessments/'),
        ),
    ]
