# Generated by Django 2.2 on 2021-06-15 18:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0068_auto_20210615_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionbatch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
