# Generated by Django 2.2 on 2021-06-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0068_auto_20210624_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresultitem',
            name='is_manually_graded',
            field=models.BooleanField(default=False),
        ),
    ]
