# Generated by Django 2.2 on 2021-06-29 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0068_auto_20210624_0611'),
        ('assessments', '0068_auto_20210618_1450'),
    ]

    operations = [
    ]
