# Generated by Django 2.2 on 2021-06-15 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0069_recognitionbatch_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognitionbatch',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed')], default='completed', max_length=255),
        ),
    ]
