# Generated by Django 2.2 on 2021-06-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0070_recognitionbatch_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='status',
            field=models.CharField(choices=[('assigned', 'Assigned'), ('generating', 'Generating'), ('ready_for_assignment', 'Ready for assignment'), ('ready_for_download', 'Ready for download'), ('ready_for_generation', 'Ready for generating'), ('ready_for_scan', 'Ready for scan'), ('scanned', 'Scanned'), ('scanning', 'Scanning'), ('scanning_error', 'Scanning error'), ('cropping', 'Cropping')], default='ready_for_generation', max_length=255),
        ),
        migrations.AlterField(
            model_name='recognitionbatch',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('cropping_completed', 'Cropping completed'), ('recognition_completed', 'Recognition completed')], default='completed', max_length=255),
        ),
    ]
