# Generated by Django 2.2 on 2021-06-29 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0071_auto_20210617_1155'),
        ('assessments', '0068_auto_20210624_0611'),
    ]

    operations = [
    ]
