# Generated by Django 2.2 on 2021-06-29 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0072_merge_20210629_0752'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentresult',
            name='status',
            field=models.CharField(choices=[('ready_for_recognition', 'Ready for recognition'), ('processing', 'Processing'), ('recognition_error', 'Recognition error'), ('recognized', 'Recognized')], default='recognized', max_length=255),
        ),
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='recognitionbatch',
            name='status',
            field=models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('cropping_completed', 'Cropping completed'), ('recognition_completed', 'Recognition completed'), ('recognition_error', 'Recognition error')], default='completed', max_length=255),
        ),
    ]
