# Generated by Django 2.2 on 2021-06-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0073_auto_20210629_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='status',
            field=models.CharField(choices=[('ready_for_recognition', 'Ready for recognition'), ('processing', 'Processing'), ('recognition_error', 'Recognition error'), ('recognized', 'Recognized'), ('viewed_recognition_error', 'Viewed recognition error')], default='recognized', max_length=255),
        ),
    ]
