# Generated by Django 2.2 on 2021-07-01 06:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0069_merge_20210629_1020'),
        ('assessments', '0076_auto_20210630_1940'),
    ]

    operations = [
    ]
