# Generated by Django 2.2 on 2021-07-01 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0076_auto_20210630_1940'),
        ('assessments', '0069_assessmentresultitem_is_manually_graded'),
    ]

    operations = [
    ]
