# Generated by Django 2.2 on 2021-07-01 06:58

import assessments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0077_merge_20210701_0655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='pdf_file',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='assessments/'),
        ),
    ]
