# Generated by Django 2.2 on 2021-07-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0078_auto_20210701_0658'),
        ('assessments', '0077_merge_20210701_0651'),
    ]

    operations = [
    ]
