# Generated by Django 2.2 on 2021-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0079_merge_20210701_0703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, upload_to='assessments/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='pdf_file',
            field=models.FileField(blank=True, upload_to='assessments/'),
        ),
    ]
