# Generated by Django 2.2 on 2021-07-30 05:50

import assessments.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0082_auto_20210726_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answersheetzip',
            name='document',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='answer_sheets/'),
        ),
        migrations.AlterField(
            model_name='assessmentfile',
            name='file',
            field=models.FileField(blank=True, storage=assessments.storage.MediaStorage(), upload_to='assessments/'),
        ),
    ]
