# Generated by Django 2.2 on 2021-08-06 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0083_auto_20210730_0550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentitem',
            name='kind',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('fib', 'Fill in the blank'), ('mc', 'Multiple choice'), ('mf', 'Math')], default='numeric', max_length=255),
        ),
    ]
