# Generated by Django 2.2 on 2021-10-01 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0084_auto_20210806_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='compare_by_characters',
            field=models.BooleanField(default=False),
        ),
    ]
