# # Generated by Django 2.2 on 2021-11-30 14:40
from django.db import migrations
from django.db.models import FileField, ImageField, Q


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0085_assessment_compare_by_characters'),
    ]

    operations = [
        migrations.AddField(
            model_name='recognizedperson',
            name='first_name_img',
            field=ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='recognizedperson',
            name='last_name_img',
            field=ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='recognizedperson',
            name='email_img',
            field=ImageField(blank=True, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='document_file',
            field=FileField(blank=True, null=True, upload_to='answer_sheets'),
        ),
        migrations.AddField(
            model_name='answersheet',
            name='preview_document_file',
            field=FileField(blank=True, null=True, upload_to='answer_sheets'),
        ),
    ]
