# # Generated by Django 2.2 on 2021-11-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0086_auto_20211130_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recognizedperson',
            name='first_name_url',
        ),
        migrations.RemoveField(
            model_name='recognizedperson',
            name='last_name_url',
        ),
        migrations.RemoveField(
            model_name='recognizedperson',
            name='email_url',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='document_url',
        ),
        migrations.RemoveField(
            model_name='answersheet',
            name='preview_document_url',
        ),
    ]
