# Generated by Django 2.2 on 2022-02-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0087_remove_urls'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentresult',
            name='assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_results', to='assessments.Assessment'),
        ),
    ]
