# Generated by Django 2.2 on 2022-03-29 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0089_auto_20220228_1742'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='answermark',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='answersheetscan',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='answersheetscanitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentresult',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentresultitem',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentresultitemmark',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='assessmentsettings',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='completedassessment',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='recognitionbatch',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='answer',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answermark',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answersheetscan',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='answersheetscanitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresult',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresultitem',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentresultitemmark',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assessmentsettings',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='completedassessment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='recognitionbatch',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
