# Generated by Django 2.2 on 2023-02-16 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_user_enabled_pulse_buttons'),
        ('assessments', '0090_auto_20220329_1228'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='completedassessment',
            unique_together={('assessment', 'result', 'student')},
        ),
    ]
